# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:55
from __future__ import unicode_literals

import ckeditor.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import meta.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('datetime', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 (HTML-\u0431\u043b\u043e\u043a)')),
                ('title_page', models.CharField(blank=True, max_length=170)),
                ('description_page', models.TextField(blank=True)),
                ('keywords_page', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('datetime', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 (HTML-\u0431\u043b\u043e\u043a)')),
                ('title_page', models.CharField(blank=True, max_length=170)),
                ('description_page', models.TextField(blank=True)),
                ('keywords_page', models.TextField(blank=True)),
                ('templates', models.CharField(blank=True, choices=[('-1', 'template-1'), ('-2', 'template-2'), ('-3', 'template-3'), ('-4', 'template-4')], max_length=15, verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d')),
                ('identifier', models.CharField(max_length=255, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0434\u043b\u044f url')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='pages.Document')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442',
                'verbose_name_plural': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('datetime', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 (HTML-\u0431\u043b\u043e\u043a)')),
                ('title_page', models.CharField(blank=True, max_length=170)),
                ('description_page', models.TextField(blank=True)),
                ('keywords_page', models.TextField(blank=True)),
                ('templates', models.CharField(blank=True, choices=[('-1', 'template-1'), ('-2', 'template-2'), ('-3', 'template-3'), ('-4', 'template-4')], max_length=15, verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d')),
                ('file', models.FileField(upload_to='documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442')),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('category_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REG', to='pages.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043d\u043e\u0440\u043c\u0430\u0442\u0438\u0432\u043d\u044b\u0445 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432')),
            ],
            options={
                'verbose_name': '\u041d\u043e\u0440\u043c\u0430\u0442\u0438\u0432\u043d\u044b\u0435 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
                'verbose_name_plural': '\u041d\u043e\u0440\u043c\u0430\u0442\u0438\u0432\u043d\u044b\u0435 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
