# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170102_2322'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('get_published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='regulations',
            managers=[
                ('get_published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='regulations',
            name='category_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REG', to='pages.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043d\u043e\u0440\u043c\u0430\u0442\u0438\u0432\u043d\u044b\u0445 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432'),
        ),
    ]
