# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170109_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446'},
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='regulations',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='regulations',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
