# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='age',
            field=models.CharField(blank=True, help_text='(\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u0442\u0440\u0430\u0446\u0438\u0438 \u0441\u043f\u0430\u043c\u0430)', max_length=10, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442'),
        ),
    ]
